// Generated by gencpp from file robot/RandomNumber.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_RANDOMNUMBER_H
#define ROBOT_MESSAGE_RANDOMNUMBER_H

#include <ros/service_traits.h>


#include <robot/RandomNumberRequest.h>
#include <robot/RandomNumberResponse.h>


namespace robot
{

struct RandomNumber
{

typedef RandomNumberRequest Request;
typedef RandomNumberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RandomNumber
} // namespace robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot::RandomNumber > {
  static const char* value()
  {
    return "5e093fd141a0ff6a0e66a47360e82cbb";
  }

  static const char* value(const ::robot::RandomNumber&) { return value(); }
};

template<>
struct DataType< ::robot::RandomNumber > {
  static const char* value()
  {
    return "robot/RandomNumber";
  }

  static const char* value(const ::robot::RandomNumber&) { return value(); }
};


// service_traits::MD5Sum< ::robot::RandomNumberRequest> should match
// service_traits::MD5Sum< ::robot::RandomNumber >
template<>
struct MD5Sum< ::robot::RandomNumberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot::RandomNumber >::value();
  }
  static const char* value(const ::robot::RandomNumberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot::RandomNumberRequest> should match
// service_traits::DataType< ::robot::RandomNumber >
template<>
struct DataType< ::robot::RandomNumberRequest>
{
  static const char* value()
  {
    return DataType< ::robot::RandomNumber >::value();
  }
  static const char* value(const ::robot::RandomNumberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot::RandomNumberResponse> should match
// service_traits::MD5Sum< ::robot::RandomNumber >
template<>
struct MD5Sum< ::robot::RandomNumberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot::RandomNumber >::value();
  }
  static const char* value(const ::robot::RandomNumberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot::RandomNumberResponse> should match
// service_traits::DataType< ::robot::RandomNumber >
template<>
struct DataType< ::robot::RandomNumberResponse>
{
  static const char* value()
  {
    return DataType< ::robot::RandomNumber >::value();
  }
  static const char* value(const ::robot::RandomNumberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MESSAGE_RANDOMNUMBER_H
