// Generated by gencpp from file test/RandomNumber.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_RANDOMNUMBER_H
#define TEST_MESSAGE_RANDOMNUMBER_H

#include <ros/service_traits.h>


#include <test/RandomNumberRequest.h>
#include <test/RandomNumberResponse.h>


namespace test
{

struct RandomNumber
{

typedef RandomNumberRequest Request;
typedef RandomNumberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RandomNumber
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::RandomNumber > {
  static const char* value()
  {
    return "5e093fd141a0ff6a0e66a47360e82cbb";
  }

  static const char* value(const ::test::RandomNumber&) { return value(); }
};

template<>
struct DataType< ::test::RandomNumber > {
  static const char* value()
  {
    return "test/RandomNumber";
  }

  static const char* value(const ::test::RandomNumber&) { return value(); }
};


// service_traits::MD5Sum< ::test::RandomNumberRequest> should match
// service_traits::MD5Sum< ::test::RandomNumber >
template<>
struct MD5Sum< ::test::RandomNumberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::RandomNumber >::value();
  }
  static const char* value(const ::test::RandomNumberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::RandomNumberRequest> should match
// service_traits::DataType< ::test::RandomNumber >
template<>
struct DataType< ::test::RandomNumberRequest>
{
  static const char* value()
  {
    return DataType< ::test::RandomNumber >::value();
  }
  static const char* value(const ::test::RandomNumberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::RandomNumberResponse> should match
// service_traits::MD5Sum< ::test::RandomNumber >
template<>
struct MD5Sum< ::test::RandomNumberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::RandomNumber >::value();
  }
  static const char* value(const ::test::RandomNumberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::RandomNumberResponse> should match
// service_traits::DataType< ::test::RandomNumber >
template<>
struct DataType< ::test::RandomNumberResponse>
{
  static const char* value()
  {
    return DataType< ::test::RandomNumber >::value();
  }
  static const char* value(const ::test::RandomNumberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_RANDOMNUMBER_H
