// Generated by gencpp from file chip_bldc_driver/Command.msg
// DO NOT EDIT!


#ifndef CHIP_BLDC_DRIVER_MESSAGE_COMMAND_H
#define CHIP_BLDC_DRIVER_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace chip_bldc_driver
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : header()
    , motor_command(0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motor_command(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _motor_command_type;
  _motor_command_type motor_command;





  typedef boost::shared_ptr< ::chip_bldc_driver::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chip_bldc_driver::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::chip_bldc_driver::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::chip_bldc_driver::Command > CommandPtr;
typedef boost::shared_ptr< ::chip_bldc_driver::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chip_bldc_driver::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chip_bldc_driver::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chip_bldc_driver::Command_<ContainerAllocator1> & lhs, const ::chip_bldc_driver::Command_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.motor_command == rhs.motor_command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chip_bldc_driver::Command_<ContainerAllocator1> & lhs, const ::chip_bldc_driver::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chip_bldc_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::chip_bldc_driver::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chip_bldc_driver::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chip_bldc_driver::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chip_bldc_driver::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chip_bldc_driver::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chip_bldc_driver::Command_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chip_bldc_driver::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ea5656f56e42b2757331b0a7720a566";
  }

  static const char* value(const ::chip_bldc_driver::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ea5656f56e42b27ULL;
  static const uint64_t static_value2 = 0x57331b0a7720a566ULL;
};

template<class ContainerAllocator>
struct DataType< ::chip_bldc_driver::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chip_bldc_driver/Command";
  }

  static const char* value(const ::chip_bldc_driver::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chip_bldc_driver::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Set Motor Command between -1000 and 1000\n"
"Header header\n"
"int16 motor_command\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::chip_bldc_driver::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chip_bldc_driver::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motor_command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chip_bldc_driver::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chip_bldc_driver::Command_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motor_command: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor_command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHIP_BLDC_DRIVER_MESSAGE_COMMAND_H
