// Generated by gencpp from file chip_bldc_driver/Status.msg
// DO NOT EDIT!


#ifndef CHIP_BLDC_DRIVER_MESSAGE_STATUS_H
#define CHIP_BLDC_DRIVER_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace chip_bldc_driver
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : header()
    , motor_operational_status(0)
    , battery_voltage(0.0)
    , mcu_temperature(0)
    , motor_command(0)
    , motor_pid_error(0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motor_operational_status(0)
    , battery_voltage(0.0)
    , mcu_temperature(0)
    , motor_command(0)
    , motor_pid_error(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _motor_operational_status_type;
  _motor_operational_status_type motor_operational_status;

   typedef float _battery_voltage_type;
  _battery_voltage_type battery_voltage;

   typedef int16_t _mcu_temperature_type;
  _mcu_temperature_type mcu_temperature;

   typedef int16_t _motor_command_type;
  _motor_command_type motor_command;

   typedef int32_t _motor_pid_error_type;
  _motor_pid_error_type motor_pid_error;





  typedef boost::shared_ptr< ::chip_bldc_driver::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chip_bldc_driver::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::chip_bldc_driver::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::chip_bldc_driver::Status > StatusPtr;
typedef boost::shared_ptr< ::chip_bldc_driver::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chip_bldc_driver::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chip_bldc_driver::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chip_bldc_driver::Status_<ContainerAllocator1> & lhs, const ::chip_bldc_driver::Status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.motor_operational_status == rhs.motor_operational_status &&
    lhs.battery_voltage == rhs.battery_voltage &&
    lhs.mcu_temperature == rhs.mcu_temperature &&
    lhs.motor_command == rhs.motor_command &&
    lhs.motor_pid_error == rhs.motor_pid_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chip_bldc_driver::Status_<ContainerAllocator1> & lhs, const ::chip_bldc_driver::Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chip_bldc_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::chip_bldc_driver::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chip_bldc_driver::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chip_bldc_driver::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chip_bldc_driver::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chip_bldc_driver::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chip_bldc_driver::Status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chip_bldc_driver::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10df97be388ae1578fee4bc1bad6eaac";
  }

  static const char* value(const ::chip_bldc_driver::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10df97be388ae157ULL;
  static const uint64_t static_value2 = 0x8fee4bc1bad6eaacULL;
};

template<class ContainerAllocator>
struct DataType< ::chip_bldc_driver::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chip_bldc_driver/Status";
  }

  static const char* value(const ::chip_bldc_driver::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chip_bldc_driver::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 5Hz status message\n"
"Header header\n"
"\n"
"int16 motor_operational_status\n"
"float32 battery_voltage\n"
"int16 mcu_temperature\n"
"int16 motor_command\n"
"int32 motor_pid_error\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::chip_bldc_driver::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chip_bldc_driver::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motor_operational_status);
      stream.next(m.battery_voltage);
      stream.next(m.mcu_temperature);
      stream.next(m.motor_command);
      stream.next(m.motor_pid_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chip_bldc_driver::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chip_bldc_driver::Status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motor_operational_status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor_operational_status);
    s << indent << "battery_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.battery_voltage);
    s << indent << "mcu_temperature: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mcu_temperature);
    s << indent << "motor_command: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor_command);
    s << indent << "motor_pid_error: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motor_pid_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHIP_BLDC_DRIVER_MESSAGE_STATUS_H
