// Generated by gencpp from file lidar/RandomNumber.msg
// DO NOT EDIT!


#ifndef LIDAR_MESSAGE_RANDOMNUMBER_H
#define LIDAR_MESSAGE_RANDOMNUMBER_H

#include <ros/service_traits.h>


#include <lidar/RandomNumberRequest.h>
#include <lidar/RandomNumberResponse.h>


namespace lidar
{

struct RandomNumber
{

typedef RandomNumberRequest Request;
typedef RandomNumberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RandomNumber
} // namespace lidar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidar::RandomNumber > {
  static const char* value()
  {
    return "5e093fd141a0ff6a0e66a47360e82cbb";
  }

  static const char* value(const ::lidar::RandomNumber&) { return value(); }
};

template<>
struct DataType< ::lidar::RandomNumber > {
  static const char* value()
  {
    return "lidar/RandomNumber";
  }

  static const char* value(const ::lidar::RandomNumber&) { return value(); }
};


// service_traits::MD5Sum< ::lidar::RandomNumberRequest> should match
// service_traits::MD5Sum< ::lidar::RandomNumber >
template<>
struct MD5Sum< ::lidar::RandomNumberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidar::RandomNumber >::value();
  }
  static const char* value(const ::lidar::RandomNumberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar::RandomNumberRequest> should match
// service_traits::DataType< ::lidar::RandomNumber >
template<>
struct DataType< ::lidar::RandomNumberRequest>
{
  static const char* value()
  {
    return DataType< ::lidar::RandomNumber >::value();
  }
  static const char* value(const ::lidar::RandomNumberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidar::RandomNumberResponse> should match
// service_traits::MD5Sum< ::lidar::RandomNumber >
template<>
struct MD5Sum< ::lidar::RandomNumberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidar::RandomNumber >::value();
  }
  static const char* value(const ::lidar::RandomNumberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar::RandomNumberResponse> should match
// service_traits::DataType< ::lidar::RandomNumber >
template<>
struct DataType< ::lidar::RandomNumberResponse>
{
  static const char* value()
  {
    return DataType< ::lidar::RandomNumber >::value();
  }
  static const char* value(const ::lidar::RandomNumberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAR_MESSAGE_RANDOMNUMBER_H
