// Generated by gencpp from file camera/RandomNumber.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_RANDOMNUMBER_H
#define CAMERA_MESSAGE_RANDOMNUMBER_H

#include <ros/service_traits.h>


#include <camera/RandomNumberRequest.h>
#include <camera/RandomNumberResponse.h>


namespace camera
{

struct RandomNumber
{

typedef RandomNumberRequest Request;
typedef RandomNumberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RandomNumber
} // namespace camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera::RandomNumber > {
  static const char* value()
  {
    return "5e093fd141a0ff6a0e66a47360e82cbb";
  }

  static const char* value(const ::camera::RandomNumber&) { return value(); }
};

template<>
struct DataType< ::camera::RandomNumber > {
  static const char* value()
  {
    return "camera/RandomNumber";
  }

  static const char* value(const ::camera::RandomNumber&) { return value(); }
};


// service_traits::MD5Sum< ::camera::RandomNumberRequest> should match
// service_traits::MD5Sum< ::camera::RandomNumber >
template<>
struct MD5Sum< ::camera::RandomNumberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera::RandomNumber >::value();
  }
  static const char* value(const ::camera::RandomNumberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera::RandomNumberRequest> should match
// service_traits::DataType< ::camera::RandomNumber >
template<>
struct DataType< ::camera::RandomNumberRequest>
{
  static const char* value()
  {
    return DataType< ::camera::RandomNumber >::value();
  }
  static const char* value(const ::camera::RandomNumberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera::RandomNumberResponse> should match
// service_traits::MD5Sum< ::camera::RandomNumber >
template<>
struct MD5Sum< ::camera::RandomNumberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera::RandomNumber >::value();
  }
  static const char* value(const ::camera::RandomNumberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera::RandomNumberResponse> should match
// service_traits::DataType< ::camera::RandomNumber >
template<>
struct DataType< ::camera::RandomNumberResponse>
{
  static const char* value()
  {
    return DataType< ::camera::RandomNumber >::value();
  }
  static const char* value(const ::camera::RandomNumberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_MESSAGE_RANDOMNUMBER_H
