// Generated by gencpp from file first/AddTwoInts.msg
// DO NOT EDIT!


#ifndef FIRST_MESSAGE_ADDTWOINTS_H
#define FIRST_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <first/AddTwoIntsRequest.h>
#include <first/AddTwoIntsResponse.h>


namespace first
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace first


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::first::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::first::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::first::AddTwoInts > {
  static const char* value()
  {
    return "first/AddTwoInts";
  }

  static const char* value(const ::first::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::first::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::first::AddTwoInts >
template<>
struct MD5Sum< ::first::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::first::AddTwoInts >::value();
  }
  static const char* value(const ::first::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::first::AddTwoIntsRequest> should match
// service_traits::DataType< ::first::AddTwoInts >
template<>
struct DataType< ::first::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::first::AddTwoInts >::value();
  }
  static const char* value(const ::first::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::first::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::first::AddTwoInts >
template<>
struct MD5Sum< ::first::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::first::AddTwoInts >::value();
  }
  static const char* value(const ::first::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::first::AddTwoIntsResponse> should match
// service_traits::DataType< ::first::AddTwoInts >
template<>
struct DataType< ::first::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::first::AddTwoInts >::value();
  }
  static const char* value(const ::first::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRST_MESSAGE_ADDTWOINTS_H
